Ram fix roles
SilvesterSchneider/CRohM pull request #161
Opened 2020-09-05 14:55 UTC by Razvanmatis

Das gesamte Rollenkonzept dahingehend überarbeitet, als das nun auch wirklich alle Rollen über JWT übermittelt werden unter Einhaltung der Nutzung des Entity Role Managers

2020-09-06 20:38 UTC, MIGeovision requested changes
Ich kann mich aus dem Programm aussperren, indem ich mir als letzter Admin die Admin rechte nehme.

2020-09-06 20:51 UTC, Razvanmatis commented
gefixt..nun hat der admin user immer die admin rolle @MIGeovision

2020-09-07 15:58 UTC, MIGeovision commented on backend/WebApi/Controllers/ContactController.cs
> +            await modService.UpdateContactAsync(userOfModification, await contactService.GetByIdAsync(id), mappedContact, await userService.IsDataSecurityEngineer(userOfModification.Id));
Funktioniert, beim nächsten mal aber bitte bescheid geben, hat gedauert bis ich gecheckt hab dass es um was ganz anderes geht.

2020-09-07 15:59 UTC, MIGeovision approved these changes
Funktioniert alles, wenn Silvester nix dagegen hat würde ich ihn heute Abend Mergen

2020-09-07 18:22 UTC, MIGeovision commented
Past

2020-09-07 18:22 UTC, merged