US17: Tab-Nav
SilvesterSchneider/CRohM pull request #190
Opened 2020-09-13 12:18 UTC by Razvanmatis

Nun ist eine Tab-Nav vorhanden, welche ein wenig hübscher ausschaut als zuvor.

2020-09-15 06:54 UTC, michellemrtn requested changes
Bitte noch folgende Punkte beheben:

- Beim Login wird gar keine Navigation angezeigt, hier sollte wieder die Navigation mit Logo angezeigt werden, wie vorher.
- Die Navigation für mobile Geräte ist verschwunden, bitte wieder einbauen!
- Der Name ist "Crohms" statt "Crohm"
- Die Beschriftungen sind zu klein, das sollte wieder dieselbe Schriftgröße sein wie die "Crohm"-Beschriftung

2020-09-15 06:54 UTC, michellemrtn commented on frontend/src/app/shared/navigation/sidenav/sidenav.component.ts
>    }
Die Variable activeLinkIndex wird nirgendwo verwendet. 
Und navLinks kann direkt initialisiert werden, dann wird der Typ 'any' nicht benötigt, der sollte nicht verwendet werden.

2020-09-19 15:47 UTC, Razvanmatis commented on frontend/src/app/shared/navigation/sidenav/sidenav.component.ts
>    }
entfernt..

2020-09-19 15:48 UTC, Razvanmatis commented on frontend/src/app/shared/navigation/sidenav/sidenav.component.ts
>    }
alle anderen punkte wurden erfüllt..

2020-09-21 16:15 UTC, michellemrtn commented
Bei mir ist die Schrift leider immer noch zu klein, außerdem werden jetzt Pfeile zum Scrollen angezeigt, obwohl eigentlich genug Platz da ist: 
![image](https://user-images.githubusercontent.com/60063612/93792345-b21e0700-fc35-11ea-86b2-2aae6a092bb7.png)

Und ich denke es macht mehr Sinn, die Navigation für mobile Geräte anstatt der normalen Navigation anzuzeigen. Aktuell wird die Navigation doppelt angezeigt:
![image](https://user-images.githubusercontent.com/60063612/93792768-3d979800-fc36-11ea-97ce-91a335a7b3b4.png)

2020-09-21 17:59 UTC, Razvanmatis commented
> 
> 
> Bei mir ist die Schrift leider immer noch zu klein, außerdem werden jetzt Pfeile zum Scrollen angezeigt, obwohl eigentlich genug Platz da ist:
> ![image](https://user-images.githubusercontent.com/60063612/93792345-b21e0700-fc35-11ea-86b2-2aae6a092bb7.png)
> 
> Und ich denke es macht mehr Sinn, die Navigation für mobile Geräte anstatt der normalen Navigation anzuzeigen. Aktuell wird die Navigation doppelt angezeigt:
> ![image](https://user-images.githubusercontent.com/60063612/93792768-3d979800-fc36-11ea-97ce-91a335a7b3b4.png)

aber etzet:
![Screenshot 2020-09-21 195710](https://user-images.githubusercontent.com/60075524/93803267-de8d4f80-fc44-11ea-809f-547abe429452.png)
![Screenshot 2020-09-21 195724](https://user-images.githubusercontent.com/60075524/93803269-df25e600-fc44-11ea-9b23-06efd1cb3d10.png)
![Screenshot 2020-09-21 195736](https://user-images.githubusercontent.com/60075524/93803270-df25e600-fc44-11ea-9619-7836777ebd8f.png)

hoffentlich passt das nun :) @michellemrtn

2020-09-24 15:19 UTC, michellemrtn commented
👍

2020-09-24 15:20 UTC, michellemrtn approved these changes

2020-09-24 15:20 UTC, merged