CUS2
SilvesterSchneider/CRohM pull request #291
Opened 2020-11-02 18:07 UTC by Razvanmatis

nun stehen checkboxen für die mehrfache auswahl von kontakten und organisationen zur verfügung
![CUS2](https://user-images.githubusercontent.com/60075524/97903005-b2361a00-1d3e-11eb-9dc4-6e0603157a67.png)
![CUS2_2](https://user-images.githubusercontent.com/60075524/97903010-b2ceb080-1d3e-11eb-8c65-72f1a0c173a3.png)

2020-11-02 18:10 UTC, Razvanmatis commented on frontend/src/app/events/events-list/events-list.component.ts
> +    if (date.getDate() === now.getDate() && date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear()) {
das ist nur ein bugfix der mir aufgefallen ist :) hat also eigentlich nichts mit dem MR zu tun..

2020-11-03 17:51 UTC, MIGeovision commented
![grafik](https://user-images.githubusercontent.com/42602771/98022174-90539a80-1e05-11eb-81a5-f01c51e10c6a.png)
Bei der Organisation sollten die ersten beiden Buchstaben der Organisation verwendet werden.

2020-11-03 17:52 UTC, MIGeovision commented
![grafik](https://user-images.githubusercontent.com/42602771/98022295-b8db9480-1e05-11eb-8425-40d755507ed3.png)
Grafikfehler bei MW

2020-11-03 17:54 UTC, MIGeovision requested changes
Die Buchstaben der Organisation stimmen nicht + bei Kontakte wird bei dem Kürzel mw in zwei Zeilen geschrieben.

Die Checkboxen funktionieren. (Auch wenn Rosa nicht so schön ist)

2020-11-03 18:34 UTC, Razvanmatis commented
> 
> 
> Die Buchstaben der Organisation stimmen nicht + bei Kontakte wird bei dem Kürzel mw in zwei Zeilen geschrieben.
> 
> Die Checkboxen funktionieren. (Auch wenn Rosa nicht so schön ist)

gefixt

2020-11-04 19:05 UTC, MIGeovision approved these changes

2020-11-04 19:21 UTC, merged