Umstellen des Datenbank Benutzers
SilvesterSchneider/CRohM pull request #292
Opened 2020-11-02 21:17 UTC by SilvesterSchneider

Der Pull Request ist nicht all zu groß und eigentlich gibt es kaum Änderungen aber es ist wichtig, dass jeder die folgende Anleitung bei sich macht.
In unserem Projekt auf dem Sharepoint habe ich ein Anleitung hinterlegt:
_CRMS - Dokumente\Sonstige Dokumente\Anleitung zu, Anlegen des CRMSAdmin.docx_
Bitte alle schritte bei euch **lokal** machen.
Den Benutzer habe ich schon im Live und Dev hinzugefügt und kann dann ab diesem PR benutzt werden.

Ab jetzt solltet ihr keine Probleme mehr haben mit dem Connectionstring oder dass ihr die Datenbank nicht anlegen könnt.

2020-11-03 18:09 UTC, MIGeovision commented
![grafik](https://user-images.githubusercontent.com/42602771/98024017-00fbb680-1e08-11eb-8a04-084fd0375017.png)
Bei mir scheitert die Anleitung leider bei Punkt 4.

2020-11-03 18:11 UTC, MIGeovision requested changes
Funktioniert bei mir nicht hänge bei der Aktivierung des sa.

Darfst dich auch gern bei mir aufschalten, wenn es für dich einfacher ist den Fehler zu finden, bei dir scheint es ja zu funktionieren, sonst hättest du keinen MR angefordert.

2020-11-09 19:53 UTC, Pantastisch commented on backend/WebApi/Startup.cs
> +            var user = Configuration["DBUser"] ?? "CRMSAdmin";
Macht das irgendwie Probleme mit der Docker config?

2020-11-09 20:40 UTC, Pantastisch submitted a review, later dismissed

2020-11-09 20:49 UTC, Razvanmatis commented
einrichtung des benutzers funzt bei mir wunderbar. jedoch bekomme ich das backend trotzdem mit dem richtigen connection string leider nicht zum laufen:
![grafik](https://user-images.githubusercontent.com/60075524/98594777-6dc5f380-22d5-11eb-8b58-0f66195e8154.png)

2020-11-09 20:51 UTC, SilvesterSchneider commented
> einrichtung des benutzers funzt bei mir wunderbar. jedoch bekomme ich das backend trotzdem mit dem richtigen connection string leider nicht zum laufen:
> ![grafik](https://user-images.githubusercontent.com/60075524/98594777-6dc5f380-22d5-11eb-8b58-0f66195e8154.png)

Hast alte DB gelöscht?
willst kurz teams?

2020-11-09 20:53 UTC, Razvanmatis commented
ok teams klingt gut

2020-11-10 22:49 UTC, Pantastisch commented
Ich habe gerade festgestellt, dass der Standard User für die DB auf Dockerbasis immer "SA" sein muss...
https://hub.docker.com/_/microsoft-mssql-server
https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-configure-environment-variables?view=sql-server-2017

Die Tests laufen deswegen nicht durch, weil der Server ohne DB Verbindung nicht hochfährt ("CRMSAdmin" gibt es nicht in der initialen DB)

Falls wir den User "CRMSAdmin" haben wollen, muss dieser in der DB zuerst mit dem "SA" user erzeugt werden, sonst läuft das ganze leider nicht

2020-11-13 07:28 UTC, SilvesterSchneider commented
> DB

Damn,
Danke Pana für den Tipp.
Werde versuchen das ganze auf SA Basis umzustellen. 
Sollte eigentlich das gleiche sein :)
Danke

2020-11-18 19:16 UTC, Pantastisch approved these changes

2020-11-19 18:25 UTC, michellemrtn approved these changes

2020-11-24 19:19 UTC, julianhof approved these changes

2020-12-03 20:31 UTC, zona95 approved these changes

2020-12-04 14:29 UTC, Razvanmatis approved these changes

2020-12-04 14:38 UTC, MIGeovision approved these changes

2020-12-04 15:01 UTC, merged