WIP: ram act2
SilvesterSchneider/CRohM pull request #295
Opened 2020-11-03 22:01 UTC by Razvanmatis

Nun kann man auf die telefonnummer bei den kontakte klicken, woraufhin ein anruf getätigt wird und direkt im anschluss ein historienelement eintrag zur erzeugung angezeigt wird

2020-11-04 20:43 UTC, Razvanmatis commented
removed WIP..you can start michelle..thx!

2020-11-06 16:27 UTC, michellemrtn requested changes
Laut Wireframe soll das Anrufen als weitere Aktion umgesetzt werden, nicht beim Klicken auf die Telefonnummer: 

https://thnuernbergde.sharepoint.com/:b:/s/CRMS/EayFcLOaJgVFmsLEXhyv078BYjU2mSfs-AHNcdUPCGssfQ?e=1WRnJd

2020-11-06 18:14 UTC, Razvanmatis commented
> 
> 
> Laut Wireframe soll das Anrufen als weitere Aktion umgesetzt werden, nicht beim Klicken auf die Telefonnummer:
> 
> https://thnuernbergde.sharepoint.com/:b:/s/CRMS/EayFcLOaJgVFmsLEXhyv078BYjU2mSfs-AHNcdUPCGssfQ?e=1WRnJd

ist nun hinzugefügt. danke für den hinweis

2020-11-06 18:36 UTC, michellemrtn approved these changes

2020-11-06 18:36 UTC, merged