Kal11
SilvesterSchneider/CRohM pull request #362
Opened 2020-11-29 19:05 UTC by julianhof

Beim Anlegen eines Events gibt man nun nicht mehr die Dauer, sondern die Endzeit an.

2020-11-30 20:05 UTC, SilvesterSchneider requested changes
Änderungen sehen alle gut aus.
Bitte noch abfangen, dass man nicht ein Event anlegen kann welches vor dem Startdatum endet.
Gibt es auch mehrtägige Events?

2020-12-05 08:02 UTC, SilvesterSchneider approved these changes

2020-12-05 11:36 UTC, SilvesterSchneider approved these changes

2020-12-07 21:31 UTC, julianhof commented
Nach der xten neuen Migration liefen jetzt auch die Tests durch... 

Soll ich jetzt den aktuellsten dev in meinen Branch ziehen damit du direkt mergen kannst oder löst du die Konflikte?

2020-12-19 14:53 UTC, Razvanmatis commented
dieses feature habe ich nun übernommen und im MR für bugfix_kal13 umgesetzt...

2020-12-19 14:54 UTC, closed without merging