ram_bug5
SilvesterSchneider/CRohM pull request #375
Opened 2020-12-07 18:48 UTC by Razvanmatis

Nun werden tatsächich nur alle gefilterten werte aus der liste der kontakte und organisationen selektiert wenn alle selektiert werden. + nun ist es auch möglich mit selektierten organisationen direkt eine neue veranstaltung zu erstellen

2020-12-13 21:13 UTC, michellemrtn approved these changes

2020-12-13 21:13 UTC, michellemrtn commented
@Razvanmatis  Kannst du noch die Konflikte lösen? Dann kann ich's mergen, funktioniert alles 👍

2020-12-14 10:13 UTC, michellemrtn requested changes

2020-12-14 10:13 UTC, michellemrtn commented on backend/WebApi/Startup.cs
> +            //connectionString = "Server=.\\SQLEXPRESS01;Database=CRMDB;Trusted_Connection=True;"; // BITTE NICHT L�SCHEN!! BRAUCHE ICH BEI DER ARBEIT!! DANKE, RAZ
Bitte den Original-Connectionstring drinlassen, sonst klappt bei den Entwicklern die Anbindung lokal nicht mehr!

2020-12-14 19:13 UTC, Razvanmatis commented on backend/WebApi/Startup.cs
> +            //connectionString = "Server=.\\SQLEXPRESS01;Database=CRMDB;Trusted_Connection=True;"; // BITTE NICHT L�SCHEN!! BRAUCHE ICH BEI DER ARBEIT!! DANKE, RAZ
naja, der ist eigentlich nicht für euch vorgesehen, da ihr ohne ihn arbeiten solltet..aber gut, habe ihn trotzdem angepasst...

2020-12-14 19:30 UTC, michellemrtn commented on backend/WebApi/Startup.cs
> +            //connectionString = "Server=.\\SQLEXPRESS01;Database=CRMDB;Trusted_Connection=True;"; // BITTE NICHT L�SCHEN!! BRAUCHE ICH BEI DER ARBEIT!! DANKE, RAZ
Ich meinte nicht den Kommentar, sondern die Zeile obendrüber Da hast du SQLEXPRESS durch SQLEXPRESS01 ersetzt, weswegen es bei mir nicht mehr läuft.

2020-12-14 19:33 UTC, Razvanmatis commented on backend/WebApi/Startup.cs
> +            //connectionString = "Server=.\\SQLEXPRESS01;Database=CRMDB;Trusted_Connection=True;"; // BITTE NICHT L�SCHEN!! BRAUCHE ICH BEI DER ARBEIT!! DANKE, RAZ
fuck :D :D :D sorry!!!!

2020-12-14 19:34 UTC, Razvanmatis commented on backend/WebApi/Startup.cs
> +            //connectionString = "Server=.\\SQLEXPRESS01;Database=CRMDB;Trusted_Connection=True;"; // BITTE NICHT L�SCHEN!! BRAUCHE ICH BEI DER ARBEIT!! DANKE, RAZ
sollte nun gefixt sein

2020-12-14 19:53 UTC, michellemrtn commented on backend/WebApi/Startup.cs
> +            //connectionString = "Server=.\\SQLEXPRESS01;Database=CRMDB;Trusted_Connection=True;"; // BITTE NICHT L�SCHEN!! BRAUCHE ICH BEI DER ARBEIT!! DANKE, RAZ
👍

2020-12-14 19:54 UTC, michellemrtn approved these changes

2020-12-14 19:54 UTC, merged