Mail und Event Angepasst
SilvesterSchneider/CRohM pull request #403
Opened 2020-12-16 17:59 UTC by MIGeovision

Links werden bei der Veranstaltung mit verschickt, diese Funktionieren auch.
Von einer Landingpage steht nix in der Aufgabe,  glaub wir brauchen aber noch eine oder ?

2020-12-16 18:28 UTC, SilvesterSchneider approved these changes

2020-12-22 06:00 UTC, SilvesterSchneider requested changes

2020-12-22 07:43 UTC, MIGeovision commented on backend/WebApi/Controllers/ContactController.cs
> +
Du Scherzkecks darüber haben wir gestern gesprochen und du meinstest ich soll es n Markus schreiben aber des is fast schon n eigener Task :D

2020-12-22 07:44 UTC, MIGeovision commented on backend/WebApi/Controllers/ContactController.cs
> +
Aber ja hast recht wird nicht laufen (Wobei das aber auch nicht zu meine Task gehört, da war ich nur drin um zu schauen wieso die Schnittstelle im Review nicht angesprochen werden konnte) -> in meinem Task is die 4200 aber auch noch fix drin

2020-12-22 07:53 UTC, SilvesterSchneider commented on backend/WebApi/Controllers/ContactController.cs
> +
😄 
Schon , aber da hab ich ja noch vorgeschlagen ein 
'''
#if DEGUB
...
'''
einzubauen. Damit könntest dann Live und Dev abfangen :)
Wenn es woanders als "ops085010.cs.ohmhs.de" dann müssen wir extra Arbeit machen und da kommt das Item für Markus ins spiel

2020-12-22 07:54 UTC, MIGeovision commented on backend/WebApi/Controllers/ContactController.cs
> +
Ok wird noch gemacht

2020-12-23 14:53 UTC, SilvesterSchneider approved these changes

2020-12-23 14:53 UTC, merged